In [2]:
# 3.3.1
import numpy as np
A = np.array([1,2,3,4])
print(A)
print(np.ndim(A)) # 차원 수
print(A.shape) # 형상 => Tuple 반환
print(A.shape[0]) # 형상 (no. of rows)

[1 2 3 4]
1
(4,)
4


In [8]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)
print(np.ndim(B))
print(B.shape)
print(B.shape[0]) # 형상 (no. of rows)
print(B.shape[1]) # 형상 (no. of cols)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
3
2


In [13]:
# 3.3.2
A = np.array([[1,2], [3,4]])
print(A.shape)
B = np.array([[5,6], [7,8]])
print(B.shape)

np.dot(A, B)

(2, 2)
(2, 2)


array([[19, 22],
       [43, 50]])

In [14]:
A = np.array([[1,2,3],[4,5,6]])
print(A.shape)
B = np.array([[1,2], [3,4], [5,6]])
print(B.shape)

np.dot(A,B)

(2, 3)
(3, 2)


array([[22, 28],
       [49, 64]])

In [16]:
C = np.array([[1,2], [3,4]])
print(C.shape)
print(A.shape)

np.dot(A, C)

(2, 2)
(2, 3)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [18]:
np.dot(C, A)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [19]:
# 3.3.3
X = np.array([1,2])
X.shape

(2,)

In [20]:
W = np.array([[1,3,5], [2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [21]:
W.shape

(2, 3)

In [22]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
