In [6]:
# 3.4.2
import numpy as np

# 활성화 함수
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [7]:
# 입력값
X = np.array([1.0, 0.5])

# 첫번째 층
W1 = np.array([
    [0.1, 0.3, 0.5],
    [0.2, 0.4, 0.6]
])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1
print(A1)

(2, 3)
(2,)
(3,)
[ 0.3  0.7  1.1]


In [10]:
Z1 = sigmoid(A1)
print(Z1)

[ 0.57444252  0.66818777  0.75026011]


In [13]:
# 두번째 층
W2 = np.array([
    [0.1, 0.4],
    [0.2, 0.5],
    [0.3, 0.6]
])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1, W2) + B2
print(A2)
Z2 = sigmoid(A2)
print(Z2)

(3,)
(3, 2)
(2,)
[ 0.51615984  1.21402696]
[ 0.62624937  0.7710107 ]


In [14]:
def identity_function(x):
    return x

In [16]:
# 세번째 층
W3 = np.array([
    [0.1, 0.3],
    [0.2, 0.4]
])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
print(A3)

Y = identity_function(A3)
print(Y)

[ 0.31682708  0.69627909]
[ 0.31682708  0.69627909]


In [18]:
# 3.4.3
def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5], [0.2,0.4,0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    
    return network


def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    
    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)

print(y)

[ 0.31682708  0.69627909]


In [19]:
# 3.5.1, Softmax Function
a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a)
print(exp_a)

[  1.34985881  18.17414537  54.59815003]


In [20]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542102


In [21]:
y = exp_a / sum_exp_a
print(y)

[ 0.01821127  0.24519181  0.73659691]


In [23]:
np.sum(y)

1.0

In [48]:
def softmax_old(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [49]:
def softmax_new(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [53]:
a = np.array([100,101,-20])
print(a)
print(softmax_old(a))
print(softmax_new(a))

[100 101 -20]
[  2.68941421e-01   7.31058579e-01   2.06214817e-53]
[  2.68941421e-01   7.31058579e-01   2.06214817e-53]


In [56]:
# 3.5.3
print(sum(softmax_old(a)))
print(sum(softmax_new(a)))

1.0
1.0
