In [1]:
# 5.5.1
class Relu:
    def __init__(self):
        self.mask = None
        
    def forward(self, x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0
        
        return out

    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout
        
        return dx

In [3]:
import numpy as np

x = np.array([[1.0, -0.5], [-2.0, 3.0]])
print(x)

[[ 1.  -0.5]
 [-2.   3. ]]


In [6]:
mask = (x <= 0)
print(mask)

[[False  True]
 [ True False]]


In [8]:
tmp = x.copy()
tmp[mask] = 0
print(tmp)

[[ 1.  0.]
 [ 0.  3.]]


In [10]:
# 5.5.2
class Sigmoid:
    def __init__(self):
        self.out = None
        
    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        
        return out

    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        
        return dx

In [11]:
# 5.6.1
X = np.random.rand(2) # input
W = np.random.rand(2, 3) # weight
B = np.random.rand(3) # bias

print(X.shape)
print(W.shape)
print(B.shape)

(2,)
(2, 3)
(3,)


In [12]:
Y = np.dot(X, W) + B
print(Y)

[ 1.18390567  1.28003635  0.607147  ]


In [14]:
# 5.6.2
X_dot_W = np.array([[0,0,0],[10,10,10]])
B = np.array([1,2,3])

print(X_dot_W)

[[ 0  0  0]
 [10 10 10]]


In [15]:
print(X_dot_W+B)

[[ 1  2  3]
 [11 12 13]]


In [17]:
dY = np.array([[1,2,3],[4,5,6]])
print(dY)

[[1 2 3]
 [4 5 6]]


In [18]:
dB = np.sum(dY, axis=0)
print(dB)

[5 7 9]


In [19]:
class Affine:
    def __init__(self, W, b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None
    
    def forward(self, x):
        self.x = x
        out = np.dot(x, self.W) + self.b
        
        return out
    
    def backward(self, dout):
        dx = np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)
        
        return dx

In [23]:
print(dY)
print(dY.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [33]:
# X = np.array([[1,1,1], [2,3,4], [1,1,1]])
# print(X)

# W = np.array([[3,0,0], [0,3,0], [0,0,3]])
# b = np.array([1,1,1])

# dot_W_plus_b = Affine(W, b)
# z = dot_W_plus_b.forward(X)
# print(z)
# print(dot_W_plus_b.backward(z))

In [34]:
import sys, os
sys.path.append(os.pardir)

In [35]:
# 5.6.3
class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None 
        self.y = None
        self.t = None
        
    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)
        return self.loss